name: first
on: [push]

jobs:
  run-first-command:
    runs-on: ubuntu-latest
    steps:
      - name: dispaly text
        run: df -h
      - name: multiline
        run: |
          php -v
          npm -v
          node -v