name: four
on: [push]

jobs:
  run-first-command:
    runs-on: ubuntu-latest
    steps:
      - name: dispaly text
        run: df -h
      - name: multiline
        run: |
          pwd
          ls -a
      - uses: actions/checkout@v4
      - name: multiline
        run: |
           ls -a